name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Compile TSC
      run: cd src && npm run tsc
    - name: Run tests
      run: npm test
